  
  
name: Run Test Procedures
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  workflow_dispatch:
    inputs:
      targetEnv:
        description: 'Target Environment'     
        required: true
      testSuite:
        description: 'Test Suite File Name'     
        required: true  
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: jfgarcia268/sfdx_vlocity_java:latest
    steps:  
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run All Test Procedures 
      run: |
        echo ${{ secrets[github.event.inputs.targetEnv] }} > env.sfdx
        sfdx force:auth:sfdxurl:store -d -a ALIAS -f env.sfdx
        vlocity runTestProcedure -job ${{ github.event.inputs.testSuite }} -sfdx.username ALIAS --verbose true --simpleLogging true 
        
